[favicons]
cfg_schema = 1

[favicons.proxy]

[favicons.proxy.resolver_map]
"duckduckgo" = "searx.favicons.resolvers.duckduckgo"
"google" = "searx.favicons.resolvers.google"

[favicons.cache]
db_url = "/var/cache/searxng/faviconcache.db"
