#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/_common.sh"

CONFIG_PATH="${VIBE_CONFIG_PATH:-}"
if [[ -z "${CONFIG_PATH}" ]]; then
  CONFIG_PATH="${HOME}/.vibe/config.toml"
fi

mkdir -p "$(dirname "${CONFIG_PATH}")"
BACKUP_PATH="${CONFIG_PATH}.devstral-infra.bak"

if [[ -f "${CONFIG_PATH}" && ! -f "${BACKUP_PATH}" ]]; then
  cp "${CONFIG_PATH}" "${BACKUP_PATH}"
fi

if [[ ! -f "${CONFIG_PATH}" ]]; then
  cat > "${CONFIG_PATH}" <<'EOF'
# Generated by devstral-infra
active_model = "local"
EOF
  echo "set active_model=local in ${CONFIG_PATH}"
  exit 0
fi

python3 - "${CONFIG_PATH}" <<'PY'
import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")

pattern = re.compile(r'(?m)^active_model\s*=\s*"[^\"]*"\s*$')
if pattern.search(text):
    text = pattern.sub('active_model = "local"', text, count=1)
else:
    text = 'active_model = "local"\n' + text

if not text.endswith("\n"):
    text += "\n"

path.write_text(text, encoding="utf-8")
PY

echo "set active_model=local in ${CONFIG_PATH}"
echo "backup (first run): ${BACKUP_PATH}"
