#!/usr/bin/env bash
# Configure Mistral Vibe CLI for local Ollama server
# Based on: https://dev.to/chung_duy_51a346946b27a3d/running-mistral-vibe-with-local-llms-a-complete-guide-1mde
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/_common.sh"

platform="$(detect_platform)"

if [[ "${platform}" == "mac" ]]; then
    MODEL_ID="${VIBE_LOCAL_MODEL_ID:-devstral-small-2}"
    PROVIDER_NAME="${VIBE_LOCAL_PROVIDER_NAME:-ollama}"
    API_BASE="${VIBE_LOCAL_API_BASE:-http://localhost:11434/v1}"
else
    # Check if Ollama is running, otherwise assume vLLM
    if pgrep -x ollama >/dev/null 2>&1; then
        MODEL_ID="${VIBE_LOCAL_MODEL_ID:-devstral-small-2}"
        PROVIDER_NAME="${VIBE_LOCAL_PROVIDER_NAME:-ollama}"
        API_BASE="${VIBE_LOCAL_API_BASE:-http://127.0.0.1:11434/v1}"
    else
        MODEL_ID="${VIBE_LOCAL_MODEL_ID:-$(default_model 2>/dev/null || echo "mistralai/Devstral-Small-2-24B-Instruct-2512")}"
        PROVIDER_NAME="${VIBE_LOCAL_PROVIDER_NAME:-local}"
        API_BASE="${VIBE_LOCAL_API_BASE:-http://127.0.0.1:8080/v1}"
    fi
fi

CONFIG_PATH="${VIBE_CONFIG_PATH:-${HOME}/.vibe/config.toml}"
mkdir -p "$(dirname "${CONFIG_PATH}")"

BACKUP_PATH="${CONFIG_PATH}.devstral-infra.bak"
if [[ -f "${CONFIG_PATH}" && ! -f "${BACKUP_PATH}" ]]; then
    cp "${CONFIG_PATH}" "${BACKUP_PATH}"
    echo "backup: ${BACKUP_PATH}"
fi

# Generate complete config based on dev.to guide
cat > "${CONFIG_PATH}" <<EOF
# Mistral Vibe CLI configuration for local Ollama
# Generated by devstral-infra
# Reference: https://dev.to/chung_duy_51a346946b27a3d/running-mistral-vibe-with-local-llms-a-complete-guide-1mde

active_model = "ollama-${MODEL_ID}"

# UI settings
textual_theme = "terminal"
vim_keybindings = false
disable_welcome_banner_animation = false

# Context settings
auto_compact_threshold = 200000
context_warnings = false

# Prompt settings
system_prompt_id = "cli"
include_commit_signature = true
include_model_info = true
include_project_context = true

# Disable auto-updates for local usage
enable_update_checks = false

# API timeout (seconds) - higher for local inference
api_timeout = 720.0

# ============================================================
# PROVIDERS
# ============================================================

[[providers]]
name = "ollama"
api_base = "${API_BASE}"
api_key_env_var = ""
api_style = "openai"
backend = "generic"
reasoning_field_name = "reasoning_content"

[[providers]]
name = "mistral"
api_base = "https://api.mistral.ai/v1"
api_key_env_var = "MISTRAL_API_KEY"
api_style = "openai"
backend = "mistral"
reasoning_field_name = "reasoning_content"

# ============================================================
# MODELS
# ============================================================

[[models]]
name = "${MODEL_ID}"
provider = "ollama"
alias = "ollama-${MODEL_ID}"
temperature = 0.15
input_price = 0.0
output_price = 0.0

[[models]]
name = "devstral-small-2"
provider = "ollama"
alias = "local"
temperature = 0.15
input_price = 0.0
output_price = 0.0

[[models]]
name = "mistral-vibe-cli-latest"
provider = "mistral"
alias = "cloud"
temperature = 0.2
input_price = 0.4
output_price = 2.0

# ============================================================
# PROJECT CONTEXT
# ============================================================

[project_context]
max_chars = 40000
default_commit_count = 5
max_doc_bytes = 32768
truncation_buffer = 1000
max_depth = 3
max_files = 1000
max_dirs_per_level = 20
timeout_seconds = 2.0

# ============================================================
# SESSION LOGGING
# ============================================================

[session_logging]
save_dir = "~/.vibe/logs/session"
session_prefix = "session"
enabled = true

# ============================================================
# TOOL PERMISSIONS
# ============================================================

[tools.read_file]
permission = "always"
max_read_bytes = 64000

[tools.write_file]
permission = "ask"
max_write_bytes = 64000

[tools.search_replace]
permission = "ask"
max_content_size = 100000

[tools.bash]
permission = "ask"
max_output_bytes = 16000
default_timeout = 30

[tools.grep]
permission = "always"
max_output_bytes = 64000
default_max_matches = 100

[tools.todo]
permission = "always"
max_todos = 100
EOF

echo "Configured Vibe for local Ollama:"
echo "- config: ${CONFIG_PATH}"
echo "- active_model: ollama-${MODEL_ID}"
echo "- provider: ${PROVIDER_NAME}"
echo "- api_base: ${API_BASE}"
echo ""
echo "Usage:"
echo "  1. Start Ollama: ollama serve"
echo "  2. Run Vibe: vibe"
echo "  3. Switch models in Vibe: /config"
