#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/_common.sh"

# Detect platform and set defaults accordingly
platform="$(detect_platform)"

if [[ "${platform}" == "mac" ]]; then
    # macOS: Use Ollama (port 11434, model name without provider prefix)
    MODEL_ID="${VIBE_LOCAL_MODEL_ID:-devstral-small-2}"
    PROVIDER_NAME="${VIBE_LOCAL_PROVIDER_NAME:-ollama}"
    API_BASE="${VIBE_LOCAL_API_BASE:-http://127.0.0.1:11434/v1}"
else
    # Linux/WSL: Use vLLM (port 8080, full HuggingFace model ID)
    MODEL_ID="${VIBE_LOCAL_MODEL_ID:-$(default_model 2>/dev/null || echo "mistralai/Devstral-Small-2-24B-Instruct-2512")}"
    PROVIDER_NAME="${VIBE_LOCAL_PROVIDER_NAME:-local}"
    API_BASE="${VIBE_LOCAL_API_BASE:-http://127.0.0.1:8080/v1}"
fi

CONFIG_PATH="${VIBE_CONFIG_PATH:-}"
if [[ -z "${CONFIG_PATH}" ]]; then
  CONFIG_PATH="${HOME}/.vibe/config.toml"
fi

mkdir -p "$(dirname "${CONFIG_PATH}")"
BACKUP_PATH="${CONFIG_PATH}.devstral-infra.bak"

if [[ -f "${CONFIG_PATH}" && ! -f "${BACKUP_PATH}" ]]; then
  cp "${CONFIG_PATH}" "${BACKUP_PATH}"
fi

if [[ ! -f "${CONFIG_PATH}" ]]; then
  cat > "${CONFIG_PATH}" <<'EOF'
# Generated by devstral-infra
active_model = "local"
EOF
fi

python3 - "${CONFIG_PATH}" "${MODEL_ID}" "${PROVIDER_NAME}" "${API_BASE}" <<'PY'
import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
model_id = sys.argv[2]
provider_name = sys.argv[3]
api_base = sys.argv[4]

text = path.read_text(encoding="utf-8")
lines = text.splitlines(keepends=True)

def set_top_level_key(lines_in: list[str], key: str, value: str) -> list[str]:
    pat = re.compile(rf'(?m)^{re.escape(key)}\s*=\s*"[^\"]*"\s*$')
    joined = "".join(lines_in)
    if pat.search(joined):
        joined = pat.sub(f'{key} = "{value}"', joined, count=1)
        return joined.splitlines(keepends=True)

    insert_at = 0
    for i, line in enumerate(lines_in):
        if line.lstrip().startswith("#") or line.strip() == "":
            continue
        insert_at = i
        break
    return lines_in[:insert_at] + [f'{key} = "{value}"\n'] + lines_in[insert_at:]

def set_top_level_bool(lines_in: list[str], key: str, value: bool) -> list[str]:
    val_str = "true" if value else "false"
    pat = re.compile(rf"(?m)^{re.escape(key)}\s*=\s*(true|false)\s*$")
    joined = "".join(lines_in)
    if pat.search(joined):
        joined = pat.sub(f"{key} = {val_str}", joined, count=1)
        return joined.splitlines(keepends=True)

    insert_at = 0
    for i, line in enumerate(lines_in):
        if line.lstrip().startswith("#") or line.strip() == "":
            continue
        insert_at = i
        break
    return lines_in[:insert_at] + [f"{key} = {val_str}\n"] + lines_in[insert_at:]

def set_top_level_int(lines_in: list[str], key: str, value: int) -> list[str]:
    pat = re.compile(rf"(?m)^{re.escape(key)}\s*=\s*[0-9_]+\s*$")
    joined = "".join(lines_in)
    if pat.search(joined):
        joined = pat.sub(f"{key} = {value}", joined, count=1)
        return joined.splitlines(keepends=True)

    insert_at = 0
    for i, line in enumerate(lines_in):
        if line.lstrip().startswith("#") or line.strip() == "":
            continue
        insert_at = i
        break
    return lines_in[:insert_at] + [f"{key} = {value}\n"] + lines_in[insert_at:]

def iter_table_blocks(lines_in: list[str], header: str) -> list[tuple[int, int]]:
    blocks: list[tuple[int, int]] = []
    i = 0
    while i < len(lines_in):
        if lines_in[i].strip() == header:
            start = i
            i += 1
            while i < len(lines_in) and not lines_in[i].lstrip().startswith("[["):
                i += 1
            blocks.append((start, i))
        else:
            i += 1
    return blocks

def parse_kv(block_lines: list[str]) -> dict[str, tuple[str, int]]:
    out: dict[str, tuple[str, int]] = {}
    kv_re = re.compile(r'^\s*([A-Za-z0-9_]+)\s*=\s*"([^"]*)"\s*$')
    for idx, line in enumerate(block_lines):
        m = kv_re.match(line)
        if not m:
            continue
        out[m.group(1)] = (m.group(2), idx)
    return out

def set_kv(block_lines: list[str], key: str, value: str) -> list[str]:
    kv = parse_kv(block_lines)
    if key in kv:
        _, idx = kv[key]
        block_lines[idx] = f'{key} = "{value}"\n'
        return block_lines
    return [block_lines[0]] + [f'{key} = "{value}"\n'] + block_lines[1:]

def ensure_provider(lines_in: list[str]) -> list[str]:
    blocks = iter_table_blocks(lines_in, "[[providers]]")
    for start, end in blocks:
        blk = lines_in[start:end]
        kv = parse_kv(blk)
        if kv.get("name", ("", -1))[0] == provider_name:
            blk = set_kv(blk, "api_base", api_base)
            blk = set_kv(blk, "api_style", "openai")
            blk = set_kv(blk, "backend", "generic")
            blk = set_kv(blk, "api_key_env_var", "")
            blk = set_kv(blk, "reasoning_field_name", "reasoning_content")
            return lines_in[:start] + blk + lines_in[end:]

    if lines_in and not lines_in[-1].endswith("\n"):
        lines_in[-1] += "\n"
    if lines_in and lines_in[-1].strip() != "":
        lines_in.append("\n")
    lines_in.extend(
        [
            "[[providers]]\n",
            f'name = "{provider_name}"\n',
            f'api_base = "{api_base}"\n',
            'api_key_env_var = ""\n',
            'api_style = "openai"\n',
            'backend = "generic"\n',
            'reasoning_field_name = "reasoning_content"\n',
            "\n",
        ]
    )
    return lines_in

def ensure_local_model(lines_in: list[str]) -> list[str]:
    blocks = iter_table_blocks(lines_in, "[[models]]")
    for start, end in blocks:
        blk = lines_in[start:end]
        kv = parse_kv(blk)
        if kv.get("alias", ("", -1))[0] == "local":
            blk = set_kv(blk, "provider", provider_name)
            blk = set_kv(blk, "name", model_id)
            return lines_in[:start] + blk + lines_in[end:]

    if lines_in and not lines_in[-1].endswith("\n"):
        lines_in[-1] += "\n"
    if lines_in and lines_in[-1].strip() != "":
        lines_in.append("\n")
    lines_in.extend(
        [
            "[[models]]\n",
            f'name = "{model_id}"\n',
            f'provider = "{provider_name}"\n',
            'alias = "local"\n',
            "temperature = 0.2\n",
            "input_price = 0.0\n",
            "output_price = 0.0\n",
            "\n",
        ]
    )
    return lines_in

lines = set_top_level_key(lines, "active_model", "local")
lines = set_top_level_bool(lines, "enable_auto_update", False)
lines = set_top_level_bool(lines, "enable_update_checks", False)
lines = set_top_level_int(lines, "auto_compact_threshold", 200000)
lines = ensure_provider(lines)
lines = ensure_local_model(lines)

out = "".join(lines)
if not out.endswith("\n"):
    out += "\n"
path.write_text(out, encoding="utf-8")

PY

echo "set active_model=local in ${CONFIG_PATH}"
echo "- provider: ${PROVIDER_NAME}"
echo "- api_base: ${API_BASE}"
echo "- model: ${MODEL_ID}"
echo "- enable_auto_update: false"
echo "- enable_update_checks: false"
echo "backup (first run): ${BACKUP_PATH}"
