#!/usr/bin/env bash
# Configure Mistral Vibe CLI for local LM Studio server
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/_common.sh"

LMSTUDIO_PORT="${LMSTUDIO_PORT:-1234}"
MODEL_ID="${VIBE_LOCAL_MODEL_ID:-mistralai/devstral-small-2-2512}"
API_BASE="http://127.0.0.1:${LMSTUDIO_PORT}/v1"

CONFIG_PATH="${VIBE_CONFIG_PATH:-${HOME}/.vibe/config.toml}"
mkdir -p "$(dirname "${CONFIG_PATH}")"

BACKUP_PATH="${CONFIG_PATH}.devstral-infra.bak"
if [[ -f "${CONFIG_PATH}" && ! -f "${BACKUP_PATH}" ]]; then
    cp "${CONFIG_PATH}" "${BACKUP_PATH}"
    echo "backup: ${BACKUP_PATH}"
fi

# Generate config for LM Studio
cat > "${CONFIG_PATH}" << TOML
# Mistral Vibe CLI configuration for LM Studio
# Generated by devstral-infra

active_model = "local"

# UI settings
textual_theme = "terminal"
vim_keybindings = false
disable_welcome_banner_animation = false

# Context settings - adjust based on model context size
auto_compact_threshold = 100000
context_warnings = false

# Prompt settings
system_prompt_id = "cli"
include_commit_signature = true
include_model_info = true
include_project_context = true

# Disable auto-updates for local usage
enable_auto_update = false
enable_update_checks = false

# API timeout (seconds) - higher for local inference
api_timeout = 720.0

# ============================================================
# PROVIDERS
# ============================================================

[[providers]]
name = "lmstudio"
api_base = "${API_BASE}"
api_key_env_var = ""
api_style = "openai"
backend = "generic"
reasoning_field_name = "reasoning_content"

[[providers]]
name = "mistral"
api_base = "https://api.mistral.ai/v1"
api_key_env_var = "MISTRAL_API_KEY"
api_style = "openai"
backend = "mistral"
reasoning_field_name = "reasoning_content"

# ============================================================
# MODELS
# ============================================================

[[models]]
name = "${MODEL_ID}"
provider = "lmstudio"
alias = "local"
temperature = 0.15
input_price = 0.0
output_price = 0.0

[[models]]
name = "glm-4.7-flash"
provider = "lmstudio"
alias = "glm"
temperature = 0.15
input_price = 0.0
output_price = 0.0

[[models]]
name = "mistral-vibe-cli-latest"
provider = "mistral"
alias = "cloud"
temperature = 0.2
input_price = 0.4
output_price = 2.0

# ============================================================
# PROJECT CONTEXT
# ============================================================

[project_context]
max_chars = 40000
default_commit_count = 5
max_doc_bytes = 32768
truncation_buffer = 1000
max_depth = 3
max_files = 1000
max_dirs_per_level = 20
timeout_seconds = 2.0

# ============================================================
# SESSION LOGGING
# ============================================================

[session_logging]
save_dir = "~/.vibe/logs/session"
session_prefix = "session"
enabled = true

# ============================================================
# TOOL PERMISSIONS
# ============================================================

[tools.read_file]
permission = "always"
max_read_bytes = 64000

[tools.write_file]
permission = "ask"
max_write_bytes = 64000

[tools.search_replace]
permission = "ask"
max_content_size = 100000

[tools.bash]
permission = "ask"
max_output_bytes = 16000
default_timeout = 30

[tools.grep]
permission = "always"
max_output_bytes = 64000
default_max_matches = 100

[tools.todo]
permission = "always"
max_todos = 100
TOML

echo "Configured Vibe for LM Studio:"
echo "- config: ${CONFIG_PATH}"
echo "- active_model: local (${MODEL_ID})"
echo "- api_base: ${API_BASE}"
echo ""
echo "Usage:"
echo "  1. Start LM Studio server: scripts/lmstudio_server_start.sh"
echo "  2. Load a model: lms load <model-path>"
echo "  3. Run Vibe: vibe"
